### ISSUE TITLE
When run app it display nothing

### ISSUE THREAD

**Issue by oddEvenAndroid** [KwabenBerko/CoinTrack-Android-MVVM#1]
I download this code and run in my system it display nothing means only white screen and here is Log for my android studio

> `D/OkHttp: <-- 404 https://coincap.io/404.html (869ms)
D/OkHttp: date: Tue, 17 Sep 2019 11:33:04 GMT
    content-type: text/html; charset=utf-8
    set-cookie: __cfduid=d7d0915bb8f3a12fb31de7b076359c7e61568719984; expires=Wed, 16-Sep-20 11:33:04 GMT; path=/; domain=.coincap.io; HttpOnly
    x-powered-by: Next.js
D/OkHttp: vary: Accept-Encoding
    cf-cache-status: HIT
    age: 99
    expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
    server: cloudflare
    cf-ray: 517ac35e8c6ad59b-BOM
D/OkHttp: <!DOCTYPE html><html><head><link rel="shortcut icon" href="/static/icons/favicon.ico" type="image/x-icon"/><link rel="apple-touch-icon" href="/static/icons/apple-touch-icon.png"/><link rel="apple-touch-icon" sizes="57x57" href="/static/icons/apple-touch-icon-57x57.png"/><link rel="apple-touch-icon" sizes="72x72" href="/static/icons/apple-touch-icon-72x72.png"/><link rel="apple-touch-icon" sizes="76x76" href="/static/icons/apple-touch-icon-76x76.png"/><link rel="apple-touch-icon" sizes="114x114" href="/static/icons/apple-touch-icon-114x114.png"/><link rel="apple-touch-icon" sizes="120x120" href="/static/icons/apple-touch-icon-120x120.png"/><link rel="apple-touch-icon" sizes="144x144" href="/static/icons/apple-touch-icon-144x144.png"/><link rel="apple-touch-icon" sizes="152x152" href="/static/icons/apple-touch-icon-152x152.png"/><link rel="apple-touch-icon" sizes="180x180" href="/static/icons/apple-touch-icon-180x180.png"/><meta name="viewport" content="width=device-width, initial-scale=1"/><meta name="keywords" content="Crypto,Cryptocurrency,Market Capitalization,Bitcoin,Ethereum,Prices,Charts"/><meta name="google" content="notranslate"/><link href="https://fonts.googleapis.com/css?family=Open+Sans:300&amp;display=swap" rel="stylesheet"/><script type="text/javascript" src="/static/charts/charting_library/charting_library.min.js"></script><script type="text/javascript" src="/static/charts/datafeeds/udf/dist/polyfills.js"></script><script type="text/javascript" src="/static/charts/datafeeds/udf/dist/bundle.js"></script><script type="text/javascript" src="https://cdn.polyfill.io/v2/polyfill.min.js"></script><style data-styled="" data-styled-version="4.3.2"></style><meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"/><meta charSet="utf-8"/><title>404: This page could not be found</title><meta name="next-head-count" content="3"/><link rel="preload" href="/_next/static/uJgfvbPp3n1MqAt6GBjob/pages/_app.js" as="script"/><link rel="preload" href="/_next/static/runtime/webpack-4b444dab214c6491079c.js" as="script"/><link rel="preload" href="/_next/static/chunks/commons.11091fde9f0f28962802.js" as="script"/><link rel="preload" href="/_next/static/runtime/main-ed629d1ce0aa6aa3f131.js" as="script"/><link rel="preload" href="/_next/static/chunks/styles.82db0a4513043701b9cd.js" as="script"/><link rel="stylesheet" href="/_next/static/css/styles.71875e2d.chunk.css"/></head><body><div><div><noscript>
            <iframe src="//www.googletagmanager.com/ns.html?id=GTM-M8N5GFF"
                height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript></div><div id="react-google-tag-manager-gtm"><script>
            (function(w,d,s,l,i){w[l]=w[l]||[];
                w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js', });
                var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';
                j.async=true;j.src='//www.googletagmanager.com/gtm.js?id='+i+dl
                ;
                f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-M8N5GFF');</script></div></div><div id="__next"><div style="color:#000;background:#fff;font-family:-apple-system, BlinkMacSystemFont, Roboto, &quot;Segoe UI&quot;, &quot;Fira Sans&quot;, Avenir, &quot;Helvetica Neue&quot;, &quot;Lucida Grande&quot;, sans-serif;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center"><div><style>body { margin: 0 }</style><h1 style="display:inline-block;border-right:1px solid rgba(0, 0, 0,.3);margin:0;margin-right:20px;padding:10px 23px 10px 0;font-size:24px;font-weight:500;vertical-align:top">404</h1><div style="display:inline-block;text-align:left;line-height:49px;height:49px;vertical-align:middle"><h2 style="font-size:14px;font-weight:normal;line-height:inherit;margin:0;padding:0">This page could not be found.</h2></div></div></div></div><script id="__NEXT_DATA__" type="application/json">{"dataManager":"[]","props":{"pageProps":{"statusCode":404},"apolloState":{"data":{}}},"page":"/_error","query":{},"buildId":"uJgfvbPp3n1MqAt6GBjob","runtimeConfig":{"GRAPHQL_URL":"https://graphql.coincap.io","WS_URL":"wss://graphql.coincap.io","TRADINGVIEW_URL":"https://trading.coincap.io","S3_STATIC_BUCKET_ENDPOINT":"https://static.coincap.io","SS_API_KEY":"a146ae5beb136639368a34a3e1c9c051219efbc666ae3f1dffb9311fa1e6be5f163ab3d94bd7e29553aedff129bd9b1995d7b345b6fc92268c910e14b4d791a0","LAUNCH_DARKLY_CLIENT_ID":"5bdcb0b70f13ed15ed55ac10"}}</script><script async="" data-next-page="/_app" src="/_next/static/uJgfvbPp3n1MqAt6GBjob/pages/_app.js"></script><script src="/_next/static/runtime/webpack-4b444dab214c6491079c.js" async=""></script><script src="/_next/static/chunks/commons.11091fde9f0f28962802.js" async=""></script><script src="/_next/static/runtime/main-ed629d1ce0aa6aa3f131.js" async=""></script><script src="/_next/static/chunks/styles.82db0a4513043701b9cd.js" async=""></script></body></html>
    <-- END HTTP (4985-byte body)
`

**Comment by KwabenBerko** [comment]
Yes, this project was created in 2018 using coincap's api. Seems like they've since changed it:

> The old CoinCap API is deprecated and was shut down on March 1, 2019. For any issues with transitioning from the old CoinCap API to the new, please submit feedback via the zendesk link above!

Check out their new api [here](https://docs.coincap.io/?version=latest) and update yours accordingly.

**Comment by oddEvenAndroid** [comment]
Can you update your project with updated Api @KwabenBerko ?

**Comment by KwabenBerko** [comment]
@oddEvenAndroid 
Yes, im planning on doing that when i get some free time.

**Comment by oddEvenAndroid** [comment]
Thanks @KwabenBerko in Advanced.
